apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-wc3q
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0047-tenant/tkrw-pr712-0075-0047-app/devfile-sample-wc3q@sha256:c98a19805a4a0e6f4403a2deb0adafeeb6cd48b8fc232c65f86f734faf49891c
        name: my-nodejs
        resources: {}
status: {}
